apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-config
  namespace: inference-service
data:
  MLFLOW_TRACKING_URI: "https://ard-mlflow.slac.stanford.edu" 
  MODEL_NAME: "lcls-cu-inj-model"
  MODEL_VERSION: "1"
