apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: inference-service
  labels:
    app: inference-service
spec:
  type: ClusterIP
  selector:
    app: inference-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
