_src_path: copier-template-k8s
container_registry: ghcr.io/slaclab/inference-service
cpu_limit: 2000m
cpu_request: 500m
memory_limit: 4Gi
memory_request: 2Gi
model_name: lcls-cu-inj-model
model_version: '1'
namespace: inference-service
replicas: 1
service_name: inference-service
